### ISSUE TITLE
torch.device Metal Performance Shaders error

### ISSUE THREAD

**Issue by JojiTokitou** [pkhungurn/talking-head-anime-demo#44] opened 2022-07-22 04:30 UTC
I'm a Japanese student. Sorry for the poor English.
When I tried this program, got error as this issue's title.
I use M1 MacBook Air and GPU is Metal Performance Shaders (MPS).
Can anybody offer me help？

**Comment by JojiTokitou** [comment] 2022-07-26 12:46
I found this error

RuntimeError: don't know how to restore data location of torch.FloatStorage (tagged with meta)

**Comment by dragonmeteor** [comment] 2022-07-28 15:30
I'm sorry to say that I might not be able to help with your problem. I don't have a MacBook with an M1 chip, so I cannot reproduce your problem.

Someone I know tried to make my system work on MacBooks. It seems that the PyTorch implementation for the M1 chip still have bugs and unimplemented features. So, you either can hack PyTorch to fix those bugs and insert unimplemented features or you can wait until the bugs are fixed by the PyTorch team.

**Closed as completed** 2023-08-11 14:30 UTC
