### ISSUE TITLE
Excuse me，I can’t upload photo.Can anybody offer me help？

### ISSUE THREAD

**Issue by AntarcticaShinn** [pkhungurn/talking-head-anime-demo#38] opened 2021-09-20 11:13 UTC
I've run the program on  anaconda .It can recognize my face，however,once I uploaded the photo,the python app/puppeteer.py
 window stucked. My GPU is RTX3070. Can anybody offer me help？

**Comment by dragonmeteor** [comment] 2021-09-29 17:50
I believe this is caused by the same problem that you experienced with the Version 2 of the software. I'm closing this bug.

**Closed by dragonmeteor** 2021-09-29 17:50 UTC
